# Generated by Django 5.2.5 on 2025-10-03 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('salario_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_despesas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resultado_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dados_calculo', models.JSONField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
